/* Generated C bindings for dotlottie-rs */

#ifndef DOTLOTTIE_PLAYER_H
#define DOTLOTTIE_PLAYER_H

/* Generated with cbindgen:0.29.2 */

/* Warning, this file is autogenerated. Do not modify this! */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
/* Type aliases for cleaner C code */
typedef struct dotlottieDotLottiePlayer DotLottiePlayer;
typedef struct dotlottieDotLottieConfig DotLottieConfig;
#define DOTLOTTIE_SUCCESS 0


#define dotlottieMAX_EVENTS 256

#define dotlottieDOTLOTTIE_SUCCESS 0

#define dotlottieDOTLOTTIE_ERROR 1

#define dotlottieDOTLOTTIE_INVALID_PARAMETER 2

#define dotlottieDOTLOTTIE_MANIFEST_NOT_AVAILABLE 3

#define dotlottieDOTLOTTIE_MAX_STR_LENGTH 512

#define dotlottieINTERACTION_TYPE_UNSET 0

#define dotlottieINTERACTION_TYPE_POINTER_UP (1 << 0)

#define dotlottieINTERACTION_TYPE_POINTER_DOWN (1 << 1)

#define dotlottieINTERACTION_TYPE_POINTER_ENTER (1 << 2)

#define dotlottieINTERACTION_TYPE_POINTER_EXIT (1 << 3)

#define dotlottieINTERACTION_TYPE_POINTER_MOVE (1 << 4)

#define dotlottieINTERACTION_TYPE_CLICK (1 << 5)

#define dotlottieINTERACTION_TYPE_ON_COMPLETE (1 << 6)

#define dotlottieINTERACTION_TYPE_ON_LOOP_COMPLETE (1 << 7)

typedef enum dotlottieMode {
  Forward,
  Reverse,
  Bounce,
  ReverseBounce,
} dotlottieMode;

typedef enum dotlottieDotLottieFit {
  Contain,
  Fill,
  Cover,
  FitWidth,
  FitHeight,
  Void,
} dotlottieDotLottieFit;

typedef enum dotlottieDotLottiePlayerEventType {
  Load = 0,
  LoadError = 1,
  Play = 2,
  Pause = 3,
  Stop = 4,
  Frame = 5,
  Render = 6,
  Loop = 7,
  Complete = 8,
} dotlottieDotLottiePlayerEventType;

typedef enum dotlottieStateMachineEventType {
  StateMachineStart = 0,
  StateMachineStop = 1,
  StateMachineTransition = 2,
  StateMachineStateEntered = 3,
  StateMachineStateExit = 4,
  StateMachineCustomEvent = 5,
  StateMachineError = 6,
  StateMachineStringInputChange = 7,
  StateMachineNumericInputChange = 8,
  StateMachineBooleanInputChange = 9,
  StateMachineInputFired = 10,
} dotlottieStateMachineEventType;

typedef struct dotlottieDotLottiePlayer dotlottieDotLottiePlayer;

typedef struct dotlottieStateMachineEngine dotlottieStateMachineEngine;

typedef struct dotlottieDotLottieLayout {
  enum dotlottieDotLottieFit fit;
  float align_x;
  float align_y;
} dotlottieDotLottieLayout;

typedef struct dotlottieDotLottieString {
  char value[dotlottieDOTLOTTIE_MAX_STR_LENGTH];
} dotlottieDotLottieString;

typedef struct dotlottieDotLottieConfig {
  enum dotlottieMode mode;
  bool loop_animation;
  uint32_t loop_count;
  float speed;
  bool use_frame_interpolation;
  bool autoplay;
  float segment_start;
  float segment_end;
  uint32_t background_color;
  struct dotlottieDotLottieLayout layout;
  struct dotlottieDotLottieString marker;
  struct dotlottieDotLottieString theme_id;
  struct dotlottieDotLottieString state_machine_id;
  struct dotlottieDotLottieString animation_id;
} dotlottieDotLottieConfig;

typedef struct dotlottieDotLottieOption_DotLottieString {
  struct dotlottieDotLottieString value;
  bool defined;
} dotlottieDotLottieOption_DotLottieString;

typedef struct dotlottieDotLottieManifest {
  struct dotlottieDotLottieOption_DotLottieString generator;
  struct dotlottieDotLottieOption_DotLottieString version;
} dotlottieDotLottieManifest;

typedef struct dotlottieDotLottieManifestAnimation {
  struct dotlottieDotLottieOption_DotLottieString id;
  struct dotlottieDotLottieOption_DotLottieString name;
  struct dotlottieDotLottieOption_DotLottieString initial_theme;
  struct dotlottieDotLottieOption_DotLottieString background;
} dotlottieDotLottieManifestAnimation;

typedef struct dotlottieDotLottieManifestTheme {
  struct dotlottieDotLottieString id;
  struct dotlottieDotLottieOption_DotLottieString name;
} dotlottieDotLottieManifestTheme;

typedef struct dotlottieDotLottieManifestStateMachine {
  struct dotlottieDotLottieString id;
  struct dotlottieDotLottieOption_DotLottieString name;
} dotlottieDotLottieManifestStateMachine;

typedef struct dotlottieDotLottieMarker {
  struct dotlottieDotLottieString name;
  float duration;
  float time;
} dotlottieDotLottieMarker;

typedef struct dotlottieLayerBoundingBox {
  float x1;
  float y1;
  float x2;
  float y2;
  float x3;
  float y3;
  float x4;
  float y4;
} dotlottieLayerBoundingBox;

typedef union dotlottieDotLottiePlayerEventData {
  float frame_no;
  uint32_t loop_count;
} dotlottieDotLottiePlayerEventData;

typedef struct dotlottieDotLottiePlayerEvent {
  enum dotlottieDotLottiePlayerEventType event_type;
  union dotlottieDotLottiePlayerEventData data;
} dotlottieDotLottiePlayerEvent;

typedef struct dotlottieDotLottieOpenUrlPolicy {
  struct dotlottieDotLottieString whitelist;
  bool require_user_interaction;
} dotlottieDotLottieOpenUrlPolicy;

typedef enum dotlottieDotLottieEvent_Tag {
  PointerDown,
  PointerUp,
  PointerMove,
  PointerEnter,
  PointerExit,
  Click,
  OnComplete,
  OnLoopComplete,
} dotlottieDotLottieEvent_Tag;

typedef struct dotlottiePointerDown_Body {
  float x;
  float y;
} dotlottiePointerDown_Body;

typedef struct dotlottiePointerUp_Body {
  float x;
  float y;
} dotlottiePointerUp_Body;

typedef struct dotlottiePointerMove_Body {
  float x;
  float y;
} dotlottiePointerMove_Body;

typedef struct dotlottiePointerEnter_Body {
  float x;
  float y;
} dotlottiePointerEnter_Body;

typedef struct dotlottiePointerExit_Body {
  float x;
  float y;
} dotlottiePointerExit_Body;

typedef struct dotlottieClick_Body {
  float x;
  float y;
} dotlottieClick_Body;

typedef struct dotlottieDotLottieEvent {
  dotlottieDotLottieEvent_Tag tag;
  union {
    dotlottiePointerDown_Body pointer_down;
    dotlottiePointerUp_Body pointer_up;
    dotlottiePointerMove_Body pointer_move;
    dotlottiePointerEnter_Body pointer_enter;
    dotlottiePointerExit_Body pointer_exit;
    dotlottieClick_Body click;
  };
} dotlottieDotLottieEvent;

typedef struct dotlottieStateMachineStringData {
  char str1[dotlottieDOTLOTTIE_MAX_STR_LENGTH];
  char str2[dotlottieDOTLOTTIE_MAX_STR_LENGTH];
  char str3[dotlottieDOTLOTTIE_MAX_STR_LENGTH];
} dotlottieStateMachineStringData;

typedef struct dotlottieStateMachineNumericData {
  char name[dotlottieDOTLOTTIE_MAX_STR_LENGTH];
  float old_value;
  float new_value;
} dotlottieStateMachineNumericData;

typedef struct dotlottieStateMachineBooleanData {
  char name[dotlottieDOTLOTTIE_MAX_STR_LENGTH];
  bool old_value;
  bool new_value;
} dotlottieStateMachineBooleanData;

typedef union dotlottieStateMachineEventData {
  struct dotlottieStateMachineStringData strings;
  struct dotlottieStateMachineNumericData numeric;
  struct dotlottieStateMachineBooleanData boolean;
} dotlottieStateMachineEventData;

typedef struct dotlottieStateMachineEvent {
  enum dotlottieStateMachineEventType event_type;
  union dotlottieStateMachineEventData data;
} dotlottieStateMachineEvent;

typedef struct dotlottieStateMachineInternalEvent {
  char message[dotlottieDOTLOTTIE_MAX_STR_LENGTH];
} dotlottieStateMachineInternalEvent;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

extern double emscripten_get_now(void);

struct dotlottieDotLottiePlayer *dotlottie_new_player(const struct dotlottieDotLottieConfig *ptr);

int32_t dotlottie_destroy(struct dotlottieDotLottiePlayer *ptr);

int32_t dotlottie_init_config(struct dotlottieDotLottieConfig *config);

int32_t dotlottie_load_animation_data(struct dotlottieDotLottiePlayer *ptr,
                                      const char *animation_data,
                                      uint32_t width,
                                      uint32_t height);

int32_t dotlottie_load_animation_path(struct dotlottieDotLottiePlayer *ptr,
                                      const char *animation_path,
                                      uint32_t width,
                                      uint32_t height);

int32_t dotlottie_load_animation(struct dotlottieDotLottiePlayer *ptr,
                                 const char *animation_id,
                                 uint32_t width,
                                 uint32_t height);

int32_t dotlottie_load_dotlottie_data(struct dotlottieDotLottiePlayer *ptr,
                                      const char *file_data,
                                      uintptr_t file_size,
                                      uint32_t width,
                                      uint32_t height);

int32_t dotlottie_manifest(struct dotlottieDotLottiePlayer *ptr,
                           struct dotlottieDotLottieManifest *result);

int32_t dotlottie_manifest_animations(struct dotlottieDotLottiePlayer *ptr,
                                      struct dotlottieDotLottieManifestAnimation *result,
                                      uintptr_t *size);

int32_t dotlottie_manifest_themes(struct dotlottieDotLottiePlayer *ptr,
                                  struct dotlottieDotLottieManifestTheme *result,
                                  uintptr_t *size);

int32_t dotlottie_manifest_state_machines(struct dotlottieDotLottiePlayer *ptr,
                                          struct dotlottieDotLottieManifestStateMachine *result,
                                          uintptr_t *size);

int32_t dotlottie_buffer_ptr(struct dotlottieDotLottiePlayer *ptr, const uint32_t **result);

int32_t dotlottie_buffer_len(struct dotlottieDotLottiePlayer *ptr, uint64_t *result);

int32_t dotlottie_config(struct dotlottieDotLottiePlayer *ptr,
                         struct dotlottieDotLottieConfig *result);

int32_t dotlottie_total_frames(struct dotlottieDotLottiePlayer *ptr, float *result);

int32_t dotlottie_duration(struct dotlottieDotLottiePlayer *ptr, float *result);

int32_t dotlottie_current_frame(struct dotlottieDotLottiePlayer *ptr, float *result);

int32_t dotlottie_loop_count(struct dotlottieDotLottiePlayer *ptr, uint32_t *result);

int32_t dotlottie_is_loaded(struct dotlottieDotLottiePlayer *ptr);

int32_t dotlottie_is_playing(struct dotlottieDotLottiePlayer *ptr);

int32_t dotlottie_is_paused(struct dotlottieDotLottiePlayer *ptr);

int32_t dotlottie_is_stopped(struct dotlottieDotLottiePlayer *ptr);

int32_t dotlottie_play(struct dotlottieDotLottiePlayer *ptr);

int32_t dotlottie_pause(struct dotlottieDotLottiePlayer *ptr);

int32_t dotlottie_stop(struct dotlottieDotLottiePlayer *ptr);

int32_t dotlottie_request_frame(struct dotlottieDotLottiePlayer *ptr, float *result);

int32_t dotlottie_set_frame(struct dotlottieDotLottiePlayer *ptr, float no);

int32_t dotlottie_seek(struct dotlottieDotLottiePlayer *ptr, float no);

int32_t dotlottie_render(struct dotlottieDotLottiePlayer *ptr);

/**
 * This is the primary method for animating in a render loop.
 *
 * It operates on a simple principle: on every call it will calculate the
 * next frame in the animation and render it. After that you just display
 * it.
 * `next_frame` is calculated based on multiple factors: the current frame
 * and the frame rate of the animation and the amount of time since the previous call.
 * Use the [DotLottiePlayer::request_frame()] method to query what frame will
 * be set and rendered on the next call to this method.
 *
 * Example of the usage
 * ```c
 *     while(true) {
 *       dotlottie_tick(player);
 *       dotlottie_buffer_ptr(player, &buffer);
 *       display(buffer, width, height);
 *     }
 * ```
 */
int32_t dotlottie_tick(struct dotlottieDotLottiePlayer *ptr);

int32_t dotlottie_resize(struct dotlottieDotLottiePlayer *ptr, uint32_t width, uint32_t height);

int32_t dotlottie_clear(struct dotlottieDotLottiePlayer *ptr);

int32_t dotlottie_is_complete(struct dotlottieDotLottiePlayer *ptr);

int32_t dotlottie_set_theme(struct dotlottieDotLottiePlayer *ptr, const char *theme_id);

int32_t dotlottie_reset_theme(struct dotlottieDotLottiePlayer *ptr);

int32_t dotlottie_set_theme_data(struct dotlottieDotLottiePlayer *ptr, const char *theme_data);

/**
 * Set slots using a JSON string
 *
 * This is the most flexible way to set slots, supporting all slot types
 * including complex gradients and animated keyframes.
 *
 * # Example JSON format
 * ```json
 * {
 *     "color_slot_id": {"p": {"a": 0, "k": [1.0, 0.0, 0.0]}},
 *     "text_slot_id": {"p": {"k": [{"t": 0, "s": {"t": "Hello"}}]}}
 * }
 * ```
 */
int32_t dotlottie_set_slots_str(struct dotlottieDotLottiePlayer *ptr, const char *slots_json);

/**
 * Clear all slots
 */
int32_t dotlottie_clear_slots(struct dotlottieDotLottiePlayer *ptr);

/**
 * Clear a specific slot by ID
 */
int32_t dotlottie_clear_slot(struct dotlottieDotLottiePlayer *ptr, const char *slot_id);

/**
 * Set a color slot with RGB values (0.0 to 1.0)
 */
int32_t dotlottie_set_color_slot(struct dotlottieDotLottiePlayer *ptr,
                                 const char *slot_id,
                                 float r,
                                 float g,
                                 float b);

/**
 * Set a scalar slot with a single float value
 */
int32_t dotlottie_set_scalar_slot(struct dotlottieDotLottiePlayer *ptr,
                                  const char *slot_id,
                                  float value);

/**
 * Set a text slot with a text string
 */
int32_t dotlottie_set_text_slot(struct dotlottieDotLottiePlayer *ptr,
                                const char *slot_id,
                                const char *text);

/**
 * Set a 2D vector slot
 */
int32_t dotlottie_set_vector_slot(struct dotlottieDotLottiePlayer *ptr,
                                  const char *slot_id,
                                  float x,
                                  float y);

/**
 * Set a 2D position slot
 */
int32_t dotlottie_set_position_slot(struct dotlottieDotLottiePlayer *ptr,
                                    const char *slot_id,
                                    float x,
                                    float y);

/**
 * Set an image slot from a file path
 */
int32_t dotlottie_set_image_slot_path(struct dotlottieDotLottiePlayer *ptr,
                                      const char *slot_id,
                                      const char *path);

/**
 * Set an image slot from a data URL (base64 encoded)
 */
int32_t dotlottie_set_image_slot_data_url(struct dotlottieDotLottiePlayer *ptr,
                                          const char *slot_id,
                                          const char *data_url);

int32_t dotlottie_markers(struct dotlottieDotLottiePlayer *ptr,
                          struct dotlottieDotLottieMarker *result,
                          uintptr_t *size);

int32_t dotlottie_active_animation_id(struct dotlottieDotLottiePlayer *ptr, char *result);

int32_t dotlottie_active_theme_id(struct dotlottieDotLottiePlayer *ptr, char *result);

int32_t dotlottie_set_viewport(struct dotlottieDotLottiePlayer *ptr,
                               int32_t x,
                               int32_t y,
                               int32_t w,
                               int32_t h);

int32_t dotlottie_segment_duration(struct dotlottieDotLottiePlayer *ptr, float *result);

int32_t dotlottie_animation_size(struct dotlottieDotLottiePlayer *ptr,
                                 float *picture_width,
                                 float *picture_height);

int32_t dotlottie_get_layer_bounds(struct dotlottieDotLottiePlayer *ptr,
                                   const char *layer_name,
                                   struct dotlottieLayerBoundingBox *result);

/**
 * Poll for the next player event from the event queue
 *
 * Returns 1 if an event was retrieved, 0 if no events are available, or -1 on error.
 * The event data is written to the event pointer.
 *
 * # Example
 * ```c
 * DotLottiePlayerEvent event;
 * while (dotlottie_poll_event(player, &event) == 1) {
 *     switch (event.event_type) {
 *         case DotLottiePlayerEventType_Load:
 *             printf("Animation loaded\n");
 *             break;
 *         case DotLottiePlayerEventType_Frame:
 *             printf("Frame: %f\n", event.data.frame_no);
 *             break;
 *     }
 * }
 * ```
 */
int32_t dotlottie_poll_event(struct dotlottieDotLottiePlayer *player,
                             struct dotlottieDotLottiePlayerEvent *event);

/**
 * Load a state machine by ID from the loaded .lottie file
 *
 * Returns a pointer to the StateMachineEngine or NULL on error.
 * The returned state machine borrows the runtime - runtime cannot be destroyed
 * while the state machine exists.
 *
 * # Safety
 * - Runtime pointer must be valid
 * - Returned state machine must be destroyed with dotlottie_state_machine_release()
 *   BEFORE destroying the runtime
 */
struct dotlottieStateMachineEngine *dotlottie_state_machine_load(struct dotlottieDotLottiePlayer *runtime,
                                                                 const char *state_machine_id);

/**
 * Load a state machine from a JSON definition string
 *
 * Returns a pointer to the StateMachineEngine or NULL on error.
 */
struct dotlottieStateMachineEngine *dotlottie_state_machine_load_data(struct dotlottieDotLottiePlayer *runtime,
                                                                      const char *state_machine_definition);

/**
 * Start the state machine with the specified URL policy
 *
 * # Returns
 * DOTLOTTIE_SUCCESS if started, DOTLOTTIE_ERROR if failed
 */
int32_t dotlottie_state_machine_start(struct dotlottieStateMachineEngine *sm,
                                      const struct dotlottieDotLottieOpenUrlPolicy *policy);

/**
 * Stop the state machine (does not release the borrow)
 *
 * Call dotlottie_state_machine_release() to actually destroy the state machine
 * and release the runtime borrow.
 */
int32_t dotlottie_state_machine_stop(struct dotlottieStateMachineEngine *sm);

/**
 * Destroy the state machine and release the runtime borrow
 *
 * After calling this, the state machine pointer is invalid and the runtime
 * can be used again.
 *
 * # Safety
 * - State machine pointer must be valid
 * - Must not use state machine pointer after this call
 */
void dotlottie_state_machine_release(struct dotlottieStateMachineEngine *sm);

/**
 * Tick the state machine (advances animation and processes state logic)
 */
int32_t dotlottie_state_machine_tick(struct dotlottieStateMachineEngine *sm);

/**
 * Post a pointer/click event to the state machine
 */
int32_t dotlottie_state_machine_post_event(struct dotlottieStateMachineEngine *sm,
                                           const struct dotlottieDotLottieEvent *event);

/**
 * Helper functions for posting specific event types
 */
int32_t dotlottie_state_machine_post_click(struct dotlottieStateMachineEngine *sm,
                                           float x,
                                           float y);

int32_t dotlottie_state_machine_post_pointer_down(struct dotlottieStateMachineEngine *sm,
                                                  float x,
                                                  float y);

int32_t dotlottie_state_machine_post_pointer_up(struct dotlottieStateMachineEngine *sm,
                                                float x,
                                                float y);

int32_t dotlottie_state_machine_post_pointer_move(struct dotlottieStateMachineEngine *sm,
                                                  float x,
                                                  float y);

int32_t dotlottie_state_machine_post_pointer_enter(struct dotlottieStateMachineEngine *sm,
                                                   float x,
                                                   float y);

int32_t dotlottie_state_machine_post_pointer_exit(struct dotlottieStateMachineEngine *sm,
                                                  float x,
                                                  float y);

/**
 * Fire a named event input
 */
int32_t dotlottie_state_machine_fire_event(struct dotlottieStateMachineEngine *sm,
                                           const char *event_name);

/**
 * Set a numeric input
 */
int32_t dotlottie_state_machine_set_numeric_input(struct dotlottieStateMachineEngine *sm,
                                                  const char *key,
                                                  float value);

/**
 * Set a string input
 */
int32_t dotlottie_state_machine_set_string_input(struct dotlottieStateMachineEngine *sm,
                                                 const char *key,
                                                 const char *value);

/**
 * Set a boolean input
 */
int32_t dotlottie_state_machine_set_boolean_input(struct dotlottieStateMachineEngine *sm,
                                                  const char *key,
                                                  bool value);

/**
 * Get a numeric input value
 */
int32_t dotlottie_state_machine_get_numeric_input(struct dotlottieStateMachineEngine *sm,
                                                  const char *key,
                                                  float *result);

/**
 * Get a string input value
 */
int32_t dotlottie_state_machine_get_string_input(struct dotlottieStateMachineEngine *sm,
                                                 const char *key,
                                                 char *result);

/**
 * Get a boolean input value
 */
int32_t dotlottie_state_machine_get_boolean_input(struct dotlottieStateMachineEngine *sm,
                                                  const char *key,
                                                  bool *result);

/**
 * Get current state name
 */
int32_t dotlottie_state_machine_current_state(struct dotlottieStateMachineEngine *sm, char *result);

/**
 * Get state machine status
 */
int32_t dotlottie_state_machine_status(struct dotlottieStateMachineEngine *sm, char *result);

/**
 * Get interaction types for framework setup
 *
 * Returns bit flags indicating which interaction types are needed.
 * Frameworks should register listeners for the returned interaction types.
 */
int32_t dotlottie_state_machine_framework_setup(struct dotlottieStateMachineEngine *sm,
                                                uint16_t *result);

/**
 * Poll for the next state machine event
 *
 * Returns 1 if an event was retrieved, 0 if no events are available, or -1 on error.
 */
int32_t dotlottie_state_machine_poll_event(struct dotlottieStateMachineEngine *sm,
                                           struct dotlottieStateMachineEvent *event);

/**
 * Poll for the next internal state machine event
 *
 * Returns 1 if an event was retrieved, 0 if no events are available, or -1 on error.
 */
int32_t dotlottie_state_machine_poll_internal_event(struct dotlottieStateMachineEngine *sm,
                                                    struct dotlottieStateMachineInternalEvent *event);

/**
 * Get the state machine definition as JSON string
 */
int32_t dotlottie_get_state_machine(struct dotlottieDotLottiePlayer *runtime,
                                    const char *state_machine_id,
                                    char *result);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* DOTLOTTIE_PLAYER_H */
